version: "3"

services:
  app:
    container_name: garimpei_rating
    image: garimpei/rating
    build: .
    volumes:
      - ".:/code/"
    ports:
      - "3001:3000"
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - NODE_ENV=DEVELOPMENT
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_DB=garimpei_rating
      - DATABASE_PORT=5432

  postgres:
    image: postgres:latest
    container_name: garimpei_rating_db
    ports:
      - "5433:5432"
    volumes:
      - ./.ignore/postgres/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=garimpei_rating

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "garimpei@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "garimpei123!"
    ports:
      - "16544:80"
    depends_on:
      - postgres
